# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
git:
  depth: 99999999
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate();
        using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs -e 'using AstroTime; AstroTime.update()'
        - julia --project=docs --color=yes docs/make.jl
      after_success: skip

